# Generated by Django 4.2.6 on 2023-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=100)),
                ('hotel_city', models.CharField(max_length=100)),
                ('hotel_state', models.CharField(max_length=100)),
                ('hotel_zipcode', models.CharField(max_length=100)),
                ('hotel_phone', models.CharField(max_length=100)),
                ('hotel_website', models.CharField(max_length=100)),
                ('hotel_rating', models.CharField(max_length=100)),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_currency', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
