# Generated by Django 4.2.6 on 2023-11-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_alter_city_latitude_alter_city_longitude'),
        ('HotelData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldata',
            name='hotel_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.city'),
        ),
    ]
