# Generated by Django 4.2.6 on 2023-11-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfLivingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.city')),
            ],
            options={
                'unique_together': {('city', 'item', 'date')},
            },
        ),
    ]
