#!/bin/bash

cat <<SQL > ./init-db.sql
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'vlad'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SQL
