# Generated by Django 4.2.6 on 2023-12-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_alter_city_latitude_alter_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='main_iata_code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
